---
- hosts: rams-staging
  gather_facts: False
  vars_files:
    - mff_vars.yml
  remote_user: "{{ rams_admin_user }}"
  tasks:

  - name: quickstart to staging
    command: git checkout mff-staging 
    args:
      chdir: "{{ quickstart_dir }}"
  - name: pull quickstart
    command: git pull
    args:
     chdir: "{{ quickstart_dir }}"
  
  - name: rams to staging
    command: git checkout mff-staging
    args:
      chdir: "{{ quickstart_dir }}/src/uber"
  - name: pull rams
    command: git pull
    args:
      chdir: "{{ quickstart_dir }}/src/uber"

  - name: plugin to staging
    command: git checkout mff-staging
    args:
      chdir: "{{ quickstart_dir }}/src/mff-rams-plugin"
  - name: pull plugin
    command: git pull
    args:
      chdir: "{{ quickstart_dir }}/src/mff-rams-plugin"

  - name: restart RAMS
    command: docker-compose -f ~/quickstart/docker-compose.yml restart web celery-worker celery-beat
